version: '3.5'
services:
  database:
    image: postgres
    volumes:
        - ./scripts/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports: 
    - 5432:5432
    env_file: ./.env.test
    